# apiVersion: v1
# kind: Service
# metadata:
#   name: netflix-app
#   labels:
#     app: netflix-app
# spec:
#   type: NodePort
#   ports:
#   - port: 80
#     targetPort: 80
#     nodePort: 30007
#   selector:
#     app: netflix-app

apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  type: LoadBalancer  # Change to LoadBalancer
  ports:
  - port: 80         # Expose port 443 for HTTPS
    targetPort: 80     # Forward traffic to port 80 in your container
    protocol: TCP
  selector:
    app: netflix-app
